/**
 * Reporter — assembles a pipeline run into a structured MigrationReport and a
 * markdown body suitable for a pull-request description.
 */

import type { ReportEntry } from "./types.js";
import type { VerifyResult } from "./verifier.js";
import type { Manifest } from "./manifest.js";

export interface MigrationReport {
  manifest: Pick<Manifest, "name" | "provider">;
  /** Files the scanner found as candidates. */
  scannedFiles: string[];
  /** Files the transform actually changed. */
  changedFiles: string[];
  /** Per-entry report from the transform. */
  entries: ReportEntry[];
  /** Verification result (may be skipped). */
  verification: VerifyResult;
  /** Summary counts for dashboards. */
  summary: {
    applied: number;
    review: number;
    changedFiles: number;
    introducedErrors: number;
    verified: boolean | "skipped";
  };
}

export function buildReport(
  manifest: Pick<Manifest, "name" | "provider">,
  scannedFiles: string[],
  changedFiles: string[],
  entries: ReportEntry[],
  verification: VerifyResult
): MigrationReport {
  const applied = entries.filter((e) => e.kind === "applied").length;
  const review = entries.filter((e) => e.kind === "review").length;
  const verified = verification.skipped
    ? ("skipped" as const)
    : verification.introduced.length === 0;
  return {
    manifest,
    scannedFiles,
    changedFiles,
    entries,
    verification,
    summary: {
      applied,
      review,
      changedFiles: changedFiles.length,
      introducedErrors: verification.introduced.length,
      verified,
    },
  };
}

/** Render a MigrationReport as a markdown PR body. */
export function reportToMarkdown(r: MigrationReport): string {
  const lines: string[] = [];
  lines.push(`## ${r.manifest.name}`);
  lines.push("");
  lines.push(
    `> Generated by **api-migrator** for the **${r.manifest.provider}** migration campaign. This PR applies deterministic, reviewable code transforms for a breaking SDK upgrade.`
  );
  lines.push("");
  lines.push("### Summary");
  lines.push(`- Files scanned: **${r.scannedFiles.length}**`);
  lines.push(`- Files changed: **${r.changedFiles.length}**`);
  lines.push(`- Transforms applied: **${r.summary.applied}**`);
  lines.push(`- Items flagged for review: **${r.summary.review}**`);
  const v = r.summary.verified;
  lines.push(
    `- Type-check: ${v === "skipped" ? "_skipped (no local TypeScript)_" : v ? "**passed** (no new errors)" : `**failed** (${r.summary.introducedErrors} new error(s))`}`
  );
  lines.push("");

  const applied = r.entries.filter((e) => e.kind === "applied");
  if (applied.length) {
    lines.push("### Applied transforms");
    for (const e of applied)
      lines.push(`- \`${e.code}\` ${loc(e)} — ${e.message}`);
    lines.push("");
  }

  const review = r.entries.filter((e) => e.kind === "review");
  if (review.length) {
    lines.push("### ⚠️ Flagged for manual review");
    lines.push("_These need a human decision and were NOT auto-applied._");
    lines.push("");
    for (const e of review) lines.push(`- \`${e.code}\` ${loc(e)} — ${e.message}`);
    lines.push("");
  }

  if (!r.verification.skipped && r.verification.introduced.length) {
    lines.push("### New type errors introduced");
    for (const e of r.verification.introduced.slice(0, 20))
      lines.push(`- \`${e.code}\` ${e.file}:${e.line ?? "?"} — ${e.message}`);
    lines.push("");
  }

  if (!review.length) {
    lines.push("_No manual review required — all changes are deterministic._");
  }
  return lines.join("\n");
}

function loc(e: ReportEntry): string {
  return e.line ? `(\`${e.file}:${e.line}\`)` : `(\`${e.file}\`)`;
}
